pipeline {
  agent {
    dockerfile {
      dir 'automation'
      reuseNode true
    }
  }
  // agent any
  stages {
    stage('Deployment') {
      when {
        branch 'main'
      }
      steps {
        sshagent(credentials: ['documentation-buildfix']) {
          // Deploy to Apache webserver
          sh 'rsync -r --delete --exclude projects/* --exclude static/font-univers . buildfix@documentation.irs.uni-stuttgart.de:/'
        }
      }
    }
  }
}
