pipeline {
  agent {
    dockerfile {
      dir 'automation'
      reuseNode true
    }
  }
  stages {
    stage('Deployment') {
      steps {
        sshagent(credentials: ['documentation-buildfix']) {
          // Deploy to Apache webserver
          sh """
          rsync -r --exclude projects/* --exclude static/font-univers \\
          . buildfix@documentation.irs.uni-stuttgart.de:/ --delete \\
          """
        }
      }
    }
  }
}
